fix: CD workflow

diff --git a/.github/workflows/nextjs-prod-CD.yml b/.github/workflows/nextjs-prod-CD.yml
--- a/.github/workflows/nextjs-prod-CD.yml
+++ b/.github/workflows/nextjs-prod-CD.yml
@@ -38,41 +38,36 @@ jobs:
         run: |
           echo "$SSH_KEY" > ssh_key
           chmod 600 ssh_key
-          
-          echo "Testing SSH connection to Bastion host"
-          ssh -i ssh_key -o StrictHostKeyChecking=no $USER@$BASTION_IP "echo 'SSH to Bastion host successful. User: $(whoami)'"
-          
+
           ssh -i ssh_key -o StrictHostKeyChecking=no $USER@$BASTION_IP << 'EOF'
-            sudo usermod -aG docker runner
-            newgrp docker
             set -x
             echo "Environment variables:"
             echo "KCR_USERNAME: $KCR_USERNAME"
             echo "KCR_PASSWORD: $KCR_PASSWORD"
             echo "DEPLOY_TAG: $DEPLOY_TAG"
             echo "WEB_IPS: $WEB_IPS"
-          
+
             IFS=',' read -ra WEB_IP_ARRAY <<< "$WEB_IPS"
-          
+
             for WEB_IP in "${WEB_IP_ARRAY[@]}"; do
               echo "Testing SSH connection to web server $WEB_IP"
               ssh -i ssh_key -o StrictHostKeyChecking=no $USER@$WEB_IP << 'ENDSSH'
                 set -x
                 echo "Docker version:"
-                docker version
+                sudo docker version
                 echo "Logging into Docker registry"
-                echo $KCR_PASSWORD | docker login dkation.kr-central-2.kcr.dev -u $KCR_USERNAME --password-stdin || { echo 'Docker login failed'; exit 1; }
+                echo $KCR_PASSWORD | sudo docker login dkation.kr-central-2.kcr.dev -u $KCR_USERNAME --password-stdin || { echo 'Docker login failed'; exit 1; }
                 echo "Stopping and removing existing containers"
-                docker ps -q --filter ancestor=dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe | xargs -r docker stop
-                docker ps -aq --filter ancestor=dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe | xargs -r docker rm
+                sudo docker ps -q --filter ancestor=dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe | xargs -r sudo docker stop
+                sudo docker ps -aq --filter ancestor=dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe | xargs -r sudo docker rm
                 echo "Removing old Docker images"
-                docker images dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe --format '{{.ID}}' | xargs -r docker rmi
+                sudo docker images dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe --format '{{.ID}}' | xargs -r sudo docker rmi
                 echo "Pulling new Docker image"
-                docker pull dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe:${DEPLOY_TAG} || { echo 'Docker pull failed'; exit 1; }
+                sudo docker pull dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe:${DEPLOY_TAG} || { echo 'Docker pull failed'; exit 1; }
                 echo "Running new Docker container"
-                docker run -d -p 80:3000 dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe:${DEPLOY_TAG} || { echo 'Docker run failed'; exit 1; }
+                sudo docker run -d -p 80:3000 dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe:${DEPLOY_TAG} || { echo 'Docker run failed'; exit 1; }
               ENDSSH
             done
           EOF
-          
+
           rm ssh_key
