fix: CD workflow

diff --git a/.github/workflows/nextjs-prod-CD.yml b/.github/workflows/nextjs-prod-CD.yml
--- a/.github/workflows/nextjs-prod-CD.yml
+++ b/.github/workflows/nextjs-prod-CD.yml
@@ -42,7 +42,7 @@ jobs:
           echo "Testing SSH connection to Bastion host"
           ssh -i ssh_key -o StrictHostKeyChecking=no $USER@$BASTION_IP "echo 'SSH to Bastion host successful. User: $(whoami)'"
           
-          ssh -i ssh_key -o StrictHostKeyChecking=no $USER@$BASTION_IP << EOF
+          ssh -i ssh_key -o StrictHostKeyChecking=no $USER@$BASTION_IP << 'EOF'
             set -x
             echo "Environment variables:"
             echo "KCR_USERNAME: $KCR_USERNAME"
@@ -50,26 +50,27 @@ jobs:
             echo "DEPLOY_TAG: $DEPLOY_TAG"
             echo "WEB_IPS: $WEB_IPS"
           
-          IFS=',' read -ra WEB_IP_ARRAY <<< "$WEB_IPS"
+            IFS=',' read -ra WEB_IP_ARRAY <<< "$WEB_IPS"
           
-          for WEB_IP in "${WEB_IP_ARRAY[@]}"; do
-            echo "Testing SSH connection to web server $WEB_IP"
-            ssh -i ssh_key -o StrictHostKeyChecking=no $USER@$WEB_IP << 'ENDSSH'
-              set -x
-              echo "Docker version:"
-              docker version
-              echo "Logging into Docker registry"
-              echo $KCR_PASSWORD | docker login dkation.kr-central-2.kcr.dev -u $KCR_USERNAME --password-stdin || { echo 'Docker login failed'; exit 1; }
-              echo "Stopping and removing existing containers"
-              docker ps -q --filter ancestor=dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe | xargs -r docker stop
-              docker ps -aq --filter ancestor=dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe | xargs -r docker rm
-              echo "Removing old Docker images"
-              docker images dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe --format '{{.ID}}' | xargs -r docker rmi
-              echo "Pulling new Docker image"
-              docker pull dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe:${DEPLOY_TAG} || { echo 'Docker pull failed'; exit 1; }
-              echo "Running new Docker container"
-              docker run -d -p 80:3000 dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe:${DEPLOY_TAG} || { echo 'Docker run failed'; exit 1; }
-            'ENDSSH'
-          done
-
+            for WEB_IP in "${WEB_IP_ARRAY[@]}"; do
+              echo "Testing SSH connection to web server $WEB_IP"
+              ssh -i ssh_key -o StrictHostKeyChecking=no $USER@$WEB_IP << 'ENDSSH'
+                set -x
+                echo "Docker version:"
+                docker version
+                echo "Logging into Docker registry"
+                echo $KCR_PASSWORD | docker login dkation.kr-central-2.kcr.dev -u $KCR_USERNAME --password-stdin || { echo 'Docker login failed'; exit 1; }
+                echo "Stopping and removing existing containers"
+                docker ps -q --filter ancestor=dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe | xargs -r docker stop
+                docker ps -aq --filter ancestor=dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe | xargs -r docker rm
+                echo "Removing old Docker images"
+                docker images dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe --format '{{.ID}}' | xargs -r docker rmi
+                echo "Pulling new Docker image"
+                docker pull dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe:${DEPLOY_TAG} || { echo 'Docker pull failed'; exit 1; }
+                echo "Running new Docker container"
+                docker run -d -p 80:3000 dkation.kr-central-2.kcr.dev/dkation-prod-front/dkation-prod-fe:${DEPLOY_TAG} || { echo 'Docker run failed'; exit 1; }
+          ENDSSH
+            done
+          EOF
+          
           rm ssh_key
